remote_theme: ddc-java/ddc-day
repository_links:
  enabled: false
page_navigator:
  enabled: true
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project.

title: "BLackjack"
description: "Blackjack for people who don't want to go to a casino or spend money."
author:
  name: "Kasmir Penn"

# Do not change the following line.
  copyright: true
