remote_theme: ddc-java/ddc-day
repository_links:
  enabled: false
page_navigator:
  enabled: false
titles_from_headings:
  enabled: false

# Modify the contents below for the specific project.

title: "New Game"
description: "An app for people who don't like looking for new games, we take games you've played
scored highly to find new game recommendations for you."
author:
  name: "Kasmir Penn"

# Do not change the following line.
  copyright: true
